name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the deployment when changes are pushed to the 'main' branch.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu to run the job.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository.

      - name: Set up Node.js (if you're using Node.js for build processes)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use Node.js version 14 (adjust based on your needs).

      - name: Install dependencies (if any)
        run: |
          npm install  # If you're using a package manager like npm, install dependencies.

      - name: Build the site (optional)
        run: |
          npm run build  # Run your build process (optional step if you use bundlers like Webpack).

      - name: Build Site
        run: echo "Building site..."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # GitHub Action to deploy to GitHub Pages.
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication.
          publish_dir: ./  # Directory to publish (use the folder where your site files are).

